#!/usr/bin/env python

import yaml
import argparse
from openstack_exporter.exporter import start_exporter

parser = argparse.ArgumentParser()
parser.add_argument('--config', type=argparse.FileType('r'), 
    default='../openstack.yaml')

args = parser.parse_args()

start_exporter(config)



print 'Staring openstack_exporter...'


